# SE_OPTS can be found at https://www.selenium.dev/documentation/grid/configuration/cli_options/

services:

  selenium-hub:
    image: selenium/hub:4.8.3-20230403
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.8.3-20230403
    shm_size: 2gb
    ports:
      - "5900"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_OPTS=--session-timeout 7200

  firefox:
    image: selenium/node-firefox:4.8.3-20230403
    shm_size: 2gb
    ports:
      - "5900"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_OPTS=--session-timeout 7200
